### ISSUE TITLE
Geophysics

### ISSUE THREAD

**Issue by RichardScottOZ** [Alberta-Geological-Survey/depth-to-bedrock#2]
Hi @stevenpawley,

How do you think you would change this if you were going to add geophysics into the mix at scale?

**Comment by stevenpawley** [comment]
Hi Richard, would love to be able to put some geophysics into the mix - I think it could help in those deep sediment areas. With the right predictors, you also might not really get any benefit to having those spatial autocorrelation features, which appear to mostly increase the model's accuracy for those deep sediment areas, where the current range of predictors are less relevant to predicting DTB
