### ISSUE TITLE
filter clarification

### ISSUE THREAD

**Issue by RichardScottOZ** [Alberta-Geological-Survey/depth-to-bedrock#3]
At here in 03-training-data.qmd

a conflict in 'filter' definition

I presume this is the one you want as it exists?

```R
picks_nlp_thinned <- picks_nlp |>
  tidyterra::filter(!row_number() %in% idx_within_dist)
```

**Comment by stevenpawley** [comment]
Thanks for that - `dplyr::filter` would be the intent
